### PR TITLE
Re-skin and remove MUI

### PR DESCRIPTION
**Pull request by benloh**
Re-skin MEME based on Evan's design and remove reliance on MUI.

### To Do
* [X] "Evidence Library"
* [X] "Evidence Link"
* [X] The width of the library is also pending a more general revamp.
* [X] Clicking "New Evidence Link" takes you to the Resource View.  It should stay in the Evidence Library view.
* [X] The ResourceView window can scroll off screen
* [X] Main View is now functional
* [X] SVG canvas is now displayed in the right place
* [X] SVG canvas properly resizes with sidebar expansion/collapse
* [x] Sidebars now scroll vertically when necessary
* [X] "Elements" tool panel now styled and operational
* [X] Control bar (selected entity/mech/outcome buttons) are now operational
* [x] Custom icons have not been added yet
* [x] SVG views still have problem layouts
* [x] Ratings are still using the "+"/"X" icons 
* [x] Final colors and layout tweaking to match Evan's design

### To Test
Focus testing just on the overall look at feel currently.  There are features/nuances that aren't implemented yet.
Packages have been updated, so don't forget to run `npm ci`.

1. `git fetch`
2. `git checkout dev-bl/de-muiify-evidence`
3. `npm run clean`
4. `npm ci`
5. `npm start` or `npm run dev`
6. Focus on the Evidence Library -- the rest of the app has not been fixed yet.  Try:
   - open resource
   - add a new evidence link
   - expand and contract the evidence link
   - edit the link text
   - attach a screenshot/image
   - link the evidence to an outcome/process/entity

### Reference
* [Figma Design](https://www.figma.com/design/4FbIFEdzZNzHrxU0FjhVOv/MEME-Fig?node-id=214-2304&t=nBAub6VmbIV0WiZ8-0)

### CODE REVIEW

**Comment by jdanish** [comment]
The parts I can see look good...  doesn't seem like much to test yet unless I'm misunderstanding?  Excited to see it develop!

**Comment by benloh** [comment]
Yeah, ideally it'd just seem to work like it did before even though we tore out all the guts and tried to hook everything back up again.

**Comment by benloh** [comment]
Archiving initial comment:

@jdanish here is a first pass at implementing Evan's design as well as removing our reliance on MUI.

Currently only the Evidence Library and Resource Views are mostly done. I changed a few things from the figma designs for various reasons (in some cases because Figma does not render exactly as it does in the browser, in other cases because it was easier to implement). Please give it a whirl to make sure you like the basic gist.  Don't worry about reporting any UX issues yet because there are still a lot of broken pieces.

I imagine we'll have to do some more tweaking.

### To Do

* [ ] "Evidence Library" navbar heading is not styled yet.
* [ ] The width of the library is also pending a more general revamp.
* [ ] Ratings are still using the "+"/"X" icons 
* [ ] Clicking "New Evidence Link" takes you to the Resource View.  It should stay in the Evidence Library view.
* [ ] The ResourceView window can scroll off screen
* [ ] All other widgets have not been converted (e.g. the right sidebar, the navbar, all the outcome/process/entity dialogs, sticky notes)

**Comment by benloh** [comment]
Much of the basics are now styled:
screenshot_1618

**Comment by benloh** [comment]
# NOTES (WIP)

#### Ratings

The Ratings system has been converted from a 7 point system using "+++" and "---" to a 5 point system using smiley faces.
Since the ratings system is custom defined for each classroom, you'll need to create a new classroom to change the ratings.  Currently there isn't an interface for changing the number of ratings.

**Comment by jdanish** [comment]
Getting a compile error:

(base) jdanish@bl-educ-0007991 meme-2023 % npm run start

> meme-2023@1.3.0 start
> node meme production

PATH         -- codebase located at: /Users/jdanish/gitcode/meme-2023/src
PATH         -- meme root folder located at: /Users/jdanish/gitcode/meme-2023


MEME EXEC    - running Development Server
MEME EXEC    - on branch dev-bl/de-muiify-evidence
LOGGER       - logging to /Users/jdanish/gitcode/meme-2023/data/logs
URSYS        - MEMEHOST production
URSYS        - STARTING UR SOCKET SERVER
UR_DB        - USING DATABASE FILE 'meme.loki'
UR_DB        - DATABASE /Users/jdanish/gitcode/meme-2023/data/db/meme.loki
UR_NET       - initializing web socket server on port 2929
URSYS        - STARTING UR WEB SERVER
UR_EXPRESS   - COMPILING WEBSERVER w/ WEBPACK - THIS MAY TAKE SEVERAL SECONDS...
WEBPACK      - ... using webpack.base.config
WEBPACK      - ... using webpack.webapp.config
UR_NET       - socket server listening on port 2929
UR_DB        - data template if needed: $blank$
UR_DB        - production: 'teachers' has 1 elements
UR_DB        - production: 'classrooms' has 1 elements
UR_DB        - production: 'groups' has 1 elements
UR_DB        - production: 'models' has 1 elements
UR_DB        - production: 'criteria' has 2 elements
UR_DB        - production: 'sentenceStarters' has 6 elements
UR_DB        - production: 'ratingsDefinitions' has 5 elements
UR_DB        - production: 'classroomResources' has 1 elements
UR_DB        - production: 'resources' has 2 elements
UR_DB        - production: 'pmcData' has 2 elements
UR_DB        - clearing session_locks on server start
UR_DB        - database ready
UR_DB        - teachers=1 classrooms=1 groups=1 models=1 criteria=2 sentenceStarters=6 ratingsDefinitions=5 classroomResources=1 resources=2 pmcData=2 
UR_EXPRESS   - ... webpack compiling
UR_EXPRESS   - ... webpack compiling
UR_EXPRESS   - ... webpack done

---
SYSTEM INITIALIZATION COMPLETE
GO TO ONE OF THESE URLS in CHROME WEB BROWSER
ADMIN    - http://localhost:3000/#/admin
STUDENTS - http://10.21.243.79:3000
---

UR_EXPRESS   - WEBSERVER LISTENING ON PORT 3000
UR_EXPRESS   - SERVING '/Users/jdanish/gitcode/meme-2023/built/web'
UR_EXPRESS   - LIVE RELOAD ENABLED
webpack built e5bb91f200396cf7c144 in 5362ms
webpack 5.90.3 compiled with 2 errors

**Comment by benloh** [comment]
# About 

This is a deep rewrite of EVERY component in the app.  We replaced all the MUI components in every render function with simpler custom components.  A few remarks:
* We initially tried a migration from MUI4 to MUI5, but quickly found that they were incompatible with each other and the migration tools that were available did not do an adequate job of conversion.
* Converting each component from MUI4 to MUI5 would have required migrating by hand.
* MUI6 has already been released, so we would have had to first migrate to 5, then soon after to 6.
* MUI migration also required a lot of node package updates (though we probably want to be doing this regardless).
* MUI seemed like a good idea at the time.  But in practice the resulting components are very dense and hard to decipher -- you end up with endless nesting of custom components which are hard to read.  This seems more suited for an Enterprise environment where you have teams of engineers who can keep a library up to date across an organization.  But for a small engineering team like ours, requires too much overhead.
* We decided that it was better for us to strip out MUI and replace the app with simple custom components using built-in HTML and CSS features.  This approach is more likely to survive future version changes.
* In all, it took about 60 hours to convert the app (including styling Evan's design along the way), with another 16 hours that were explicitly about matching Evan's design.


## Not Done Yet
- [ ] Starting from a `_blank` database results in some errors in the admin interface.
- [ ] The comment system will be completely replaced.  That's coming up next.  So the comment buttons and basic functionality is still the old system.
- [ ] "Increasing"/"Decreasing" labels -- I have some concerns with this.  Current noted here: #28.  This is new functionality.  It's not clear to if if this is an absolute must-have for September?
- [ ] PrintMain needs to be converted.


## Caveats

There are many subtle aspects of Evan's design that have not yet been implemented.  We wanted to focus first on functionality and reserving budget for other critical systems (e.g. comment system, template system, Turbo360/Digital Ocean deployment, use auth).

- [ ] Hover colors for buttons, entity/process/outcome widgets
- [ ] Background images
- [ ] Mech Arrows
- [ ] Mech Dialog 
   - [ ] Reversing arrow direction still uses the old button approach -- and the switch arrow animation is no longer active
   - [ ] Select arrowheads does not work -- we use the old One Way / Two Way toggle switch.
- [ ] Evidence Badge with integrated ratings -- There was some question about the proper design for this.  I think Evan might need to take another pass at this. [Figma Comment Thread](https://www.figma.com/design/4FbIFEdzZNzHrxU0FjhVOv?node-id=307-8162&m=dev#856737281)
- [ ] Background image on Login screen
- [ ] Many of the custom icons have not been implemented yet (e.g. Home, Logout, Add Entity plus sign, resource type icons.

My general plan with this is to treat these as nice-to-haves once we have the key Sept pilot functionality is out the door.  But if there are aspects of the design that need to be fixed, please add them as new issues.


# To Test

You'll want to do a pretty thorough test of ALL the features (with the exception of the Comment system and PrintMain, neither of which have been converted yet).  Enough has changed that there may be subtle 

Libraries have been added, and the ratings system has changed.  So ideally you start with a new set of teacher/classroom/etc definitions.  You can use an existing one, but you'll find the ratings don't quite match.

```
git fetch
git checkout dev-bl/de-muiify-evidence
npm run clean
npm ci
npm start or npm run dev
Define a new teacher/classroom/etc.
```

**Comment by jdanish** [comment]
> "Increasing"/"Decreasing" labels

Not a must have for September - just part of our long-term thinking.

**Comment by jdanish** [comment]
Minor bug - if you double-click in the table cells it goes into "edit mode" but a) might say "object object" in some cases, and b) doesn't actually save edits, so that should be ignored.

**Comment by benloh** [comment]
> Minor bug - if you double-click in the table cells it goes into "edit mode" but a) might say "object object" in some cases, and b) doesn't actually save edits, so that should be ignored.

Oh nifty.  I had no idea we could do that :).  It should be read-only now: 8d571bfdda432513ce4c0cf735f7460c263cb944

**Comment by jdanish** [comment]
Confirmed. Yeah, it's quite cool and I could imagine some day in the future wanting to use it to edit tables in net.create (or maybe in the template editor, or beyond).

**Comment by jdanish** [comment]
Still tinkering (so-far, so-good) though I did notice that moving elements etc., around in Safari is still not working in case that is relevant.

**Comment by jdanish** [comment]
In the model list (in admin mode), the model names are clickable but don't do anything. I assume we'd either want them not to be buttons or have them open up the model?

**Comment by jdanish** [comment]
Home button in models should be a button (it works but doesn't highlight / show finger cursor)

Also, in viewing another model, the top nav is properly disabled, but you can click edit on an evidence link (you shouldn't be able to), though you cannot save (shouldn't be an issue if edit works).

**Comment by benloh** [comment]
> safari
Yes.  I just tested it yesterday and it's still broken.  #3.

# To Do
- [ ] In the model list (in admin mode), the model names are clickable but don't do anything. I assume we'd either want them not to be buttons or have them open up the model? -- Original functionality does not have teachers opening up student models directly in admin view, so I'm inclined to keep with that.
- [ ] Title column does not sort (the others do).
- [ ] Home button in models should be a button (it works but doesn't highlight / show finger cursor)
- [ ] In viewing a model made by a different user / group, the top nav is properly disabled, but you can click edit on an evidence link (you shouldn't be able to), though you cannot save (shouldn't be an issue if edit works).

**Comment by jdanish** [comment]
> Original functionality does not have teachers opening up student models directly in admin view, so I'm inclined to keep with that. 

That's fine. Some day, when we've revamped the login process it'd be nice to have that option, but not a rush at all.

**Comment by jdanish** [comment]
This seems stable aside from the to-dos above. One minor UI thing I wanted to check on was the inclusion of a classroom-level image in the bottom left? It's not technically exciting, but the teacher we'll be returning to this year really wanted it, so if that's easy to do that'd be awesome.

**Comment by benloh** [comment]
Updates
* Model titles are now not clickable in the admin interface.  -- Making project titles clickable in the admin interface is not easy because opening a project assumes a user is logged in.  Teachers can log in and open projects, but the admin user does not have a login.
* Titles can now be sorted
* Home button is now an icon button
* Evidence Link editing is now disabled for non-authors

> . One minor UI thing I wanted to check on was the inclusion of a classroom-level image in the bottom left? It's not technically exciting, but the teacher we'll be returning to this year really wanted it, so if that's easy to do that'd be awesome.

You're talking about this?
screenshot_1644
I assume you want each classroom to have an image that they can add?  

I think the key is figuring out how to add that.  e.g. are we using the resources in the resources folder?  a URL to an image hosted on a web site (assuming it's not blocked)?  And figuring out how much of a UI we need to make it work.
Not sure if it's worth the trouble, but I wonder if we could use the resource library as a way to handle that -- e.g. add another checkbox that says "Make this the theme image" or something to that effect, and then perhaps only allow images and not PDFs.

**Comment by jdanish** [comment]
> You're talking about this?

Yeah, it's not technically exciting, but it feels like a major need. Yes, ideally teachers could select per classroom. Happy to put images in the resource folder for it, and happy to use a similar interface to pick them. We still need pdfs for other resources but can certainly limit this to images. I'm all for just using the added checkbox like you mention, or making a separate line that just says "select interface image for this course". Whatever is fastest.

**Comment by jdanish** [comment]
Sorting still seems funny, but everything else seems good.

https://github.com/user-attachments/assets/566a7596-3384-4cd7-a127-aa4127eaf1d5

**Comment by benloh** [comment]
> Sorting still seems funny, but everything else seems good.

Sorry 'bout that.  It was working for 2 items...but was not properly accounting for the changed sort order for more than 2.  Should be fixed now.

**Comment by jdanish** [comment]
No worries. Confirmed this works so marking this for merge and assuming we'll handle that image separately?

**Review by jdanish — APPROVED** [review]

**Comment by benloh** [comment]
Merging these changes.  New features will be implemented in a new branch.

**Pull request merged**
