### PR TITLE
FIX: Build System Configuration Errors

### PR DESCRIPTION
**Pull request by dsriseah**
This claimfixes #19 regarding ESLint errors in the VSCODE IDE, as well as some related lint config issues. 

ALSO
- added `vs-env` script that provides environmental information when running in the VSCODE Integrated Terminal
- replaced references to `meme-boilerplate` with `meme-2023`

### TESTING VS-ENV

The `vs-env` script runs if you open the `meme-2023.code-workspace`. It has settings in it that check the environment, producing output like:
image

This is helpful for testing ARCHITECTURE and NODE VERSION MISMATCHES.

- Make sure that the terminal is reporting the correct node version, and follow prompts to correct the issue.

### TESTING ERROR-FREE OPEN

First, open meme-2023 dev branch (pre-fix) and confirm ESLint error in the OUTPUT pane of terminal for ESLint
image

Next, pull the `dev-sri/build-config-fixes` branch, close VSCODE, and reopen it. 
- Check that there is no ESLint config "Error: "prettier/react" has been merged into "prettier" in eslint-config-prettier" appearing in the output pane for ESLint (see above screenshot for where to find it)

### TESTING BUILD

- `npm ci && npm run dev`
- check that admin, project works at least to the first student screen without errors in the console
- **ignore** cosmetic and alignment issues in screen; that is a separate issue

---
## Known Issues

- There are more than a few linting errors in the files now, due to the change in eslint configuration. I'm not sure if the "error" in #19 has always been there...I don't recall seeing it before. I'll have to go through file-by-file and update our ESLint ruleset. Maybe there was a version bump with LTS/Hydrogen that emerged it somehow.

### CODE REVIEW

**Comment by dsriseah** [comment]
noting **unexpected npm ci errors**
After adding vs-env script, it caught that I was not in the right version of node and so I did `nvm use` followed by `npm ci` to load the correct modules. 

image

Note that I'm on ARM.

**Comment by Sakelun** [comment]
@dsriseah Before you chase that too far, these warnings exist on non-ARM systems as well.

**Comment by dsriseah** [comment]
> @dsriseah Before you chase that too far, these warnings exist on non-ARM systems as well.

Thanks! I'll open a new issue to resolve that sometime in the future.

**Comment by benloh** [comment]
Fixed and merged.  Thanks, @dsriseah!

**Pull request merged**
