### PR TITLE
Feature: Templated Comment System

### PR DESCRIPTION
**Pull request by benloh**
This is a fairly significant change.

This is a implementation of the Comment Template system from Net.Create.  See [Feature: Comment Template](https://github.com/netcreateorg/netcreate-itest/pull/236).

Much of this work also involved implementing Evan's [Figma Designs](https://www.figma.com/design/4FbIFEdzZNzHrxU0FjhVOv/MEME-Fig?node-id=331-9473&node-type=symbol&m=dev), including restyling the evidence badges.

Because MEME is architected differently from Net.Create, there are significant differences in how the two systems work under the hood.  However, most of the visible aspects should be similar.

## Features

Comments can be added to:
* The Project (next to project title)
* Any Entity
* Any Outcome
* Any Process
* Any Evidence Link

The **comment status bar** (in the app bar) displays any new comments across the network added as well as a count of the "unread replies to me" and total "unread" comment count.
* New comments and comment updates pop up and slowly fade in the status bubble
* The summary view shows just the counts of Unread and Unread Replies to Me.
* Hovering over the summary view shows the labels for Unread/Replies to Me.
* Clicking on the summary opens up a full list of new/updated comments.
* Clicking on the referent name will open the object (the object that has the comment attached).
* Clicking on the comment number will open the comment.
* Clicking "Mark All Read" will mark all of the comments read.
* "Close" will close the summary view.

### Other Notes
* Evidence Resources -- The old system had a "Notes" field that allowed users to add notes about a resource.  We used the StickyNotes system to store the notes.  Since "Notes" are no longer used, we had to remove some old code in `EVResourceItemDialog` that was used to render the note.

## To Test

1. `git checkout dev-bl/urcomment`
2. `npm run clean:all`
3. `npm ci`
4. `npm run start` or `npm run dev`
5. Create any project admin data if necessary

## To Do
- [x] Deleting comments is not implemented yet.
- [x] Clicking on the comment status referent to open the referent and comment number to open the comment is not currently implemented.  These are fairly complicated operations requiring multiple steps.
- [x] Changes in ratings are not reflected in the evidence badges yet.
- [x] Show comments in props/mechs only when selected (or has a comment).  Remove "Add Comment" button.
- [x] Clicking Evidence Link comment button opens window way to the left of the screen -- can't reproduce
- [x] Comment templates are currently burned in.

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish If we need to have admin support for editing/managing comment templates immediately, we might need to do some triage about what to implement first/next.

**Comment by jdanish** [comment]
No, we can go in whatever order makes sense for you thanks.

**Comment by jdanish** [comment]
For clarity on the comments, please add the "type" in some manner above the displayed comment. In Evan's mockup it reads "Critera: Clarity" but I think we want to just assume it is "Clarity" or "Evidence" using the existing label field. If we really want criteria in there we'd change the label "Criteria: Clarity" so that the same change / heading works in both MEME and net.create and for non-criteria things. No rush since I'll demo as-is.

**Comment by jdanish** [comment]
Sweet! One minor thing - it seems like deleting a comment generates a popup that you have a new comment, but I think that'd be one case we want to ignore if it is easy?

**Comment by jdanish** [comment]
Also, the comment notification thing appears to stick around when you go back to the models screen, but doesn't work (removing it is fine). I suppose long-term we might want new comment counts on the models in the list, but next grant ... 

Screenshot 2024-10-09 at 3 57 05 PM

**Comment by jdanish** [comment]
Also, in admin control panel when you click "add" to create a new student, it pre-fills with the last student name which doesn't seem useful.

**Comment by jdanish** [comment]
As I tinker, while this isn't a big deal, I noticed that in all popup edit boxes, the darker button (save) does not trigger on return, but the cancel does. Is that an easy change? I don't know if kids use return but I do!

**Comment by benloh** [comment]
> deleting a comment generates a popup that you have a new comment, but I think that'd be one case we want to ignore if it is easy?

I think we should be able to detect that.  I was starting to do that before I was looking at why DO stopped working.

> admin control panel when you click "add" to create a new student, it pre-fills with the last student name which doesn't seem useful.

Added #66.

>comment notification thing appears to stick around when you go back to the models screen, but doesn't work (removing it is fine)
> I noticed that in all popup edit boxes, the darker button (save) does not trigger on return, but the cancel does. Is that an easy change? I don't know if kids use return but I do!

Yes.  There's a lot of post-MUI refinements that I haven't quite gotten to.  
Comments also remain open when going back to the model view.  That's on my list.
The "Enter" issue is one of the ones that came up during our last load test.  Added #65.

**Comment by jdanish** [comment]
Is this a known issue - sorry if it is: 

1. Open model 1
2. Go back to models and open model 2
3. The elements from model 1 are now in model 2

Reload screen. Model 1 and 2 are now separate.

A graduate student ran into this when creating a new model and ended up with multiple new models that are all synced,..  I assume related but not sure?  Once refreshed and the extra deleted it seems OK.

Once the first part of this is resolved I can try and figure out if I can reproduce the second part.

**Comment by benloh** [comment]
> Is this a known issue - sorry if it is...ended up with multiple new models that are all synced

Yes.  Unfortunately this is more MUI-migration related nonsense.

**Comment by jdanish** [comment]
Cool, then no need to report it!  Thanks!

**Comment by jdanish** [comment]
Apologies if this is already know "MUI-migration nonsense" but if you click on an evidence link on the model, when it opens the link on the right it suddenly hides the top nav bar. Reloading brings it back. Or weirdly if I open the debug console to look for errors (none there) and then close it, the nav bar returns.

Screenshot 2024-10-10 at 12 16 22 PM

**Comment by benloh** [comment]
> Apologies if this is already know "MUI-migration nonsense" but if you click on an evidence link on the model, when it opens the link on the right it suddenly hides the top nav bar. Reloading brings it back. Or weirdly if I open the debug console to look for errors (none there) and then close it, the nav bar returns.

I haven't seen this.  Can you make a video of this?  I can't reproduce it.

**Comment by jdanish** [comment]
> I haven't seen this. Can you make a video of this? I can't reproduce it.

Sending via slack.

**Comment by jdanish** [comment]
I realize this might not be ready for testing, but in case you were unaware, if you try and open a comment now, nothing happens and this error appears. If there was no comment you can create one, and then if you return to the model screen, come back and open it, this error still appears (so it doesn't seem related to old data). 

Screenshot 2024-10-14 at 1 55 58 PM

**Comment by benloh** [comment]
Sorry I should not have pushed those last changes.  I'll try not to waste your time with untested pushes.

**Comment by jdanish** [comment]
No worries - I try not to test until you tell me to, but I was tweaking the comments burned in to test the experience of them and grabbed your code. All good - I can always roll back if I really need.

**Comment by benloh** [comment]
@jdanish I think we're finally ready for QA on the comment system.  Comment templates still need to be worked out.

**Comment by jdanish** [comment]
Thanks @benloh 

Default value for the top level rating seems to be "code" instead of Strongly Agrees?

Also, while npm run dev works, npm run start loads but then if I select a teacher it spins. No error, but it freezes then browser says it is unresponsive. I can delete the data and re-start, but is that expected?

**Comment by benloh** [comment]
> Default value for the top level rating seems to be "code" instead of Strongly Agrees?

Sorry.  Debug code.  Should be fixed now.

> if you load the teacher panel and scroll down so that the widgets go off-screen, it eventually freezes and you can't scroll back. Reload fixes it.
> -- this is not a bug it seems, but leaving in case it pops up --

Weird.  I saw this happen twice, but it's not consistent.  But when I grabbed the scrollbar with my mouse (instead of the mousewheel) I was able to get it to move.  It's possible some component is somehow getting the focus.  I'll file a bug so we have a record.

> Also, while npm run dev works, npm run start loads but then if I select a teacher it spins. No error, but it freezes then browser says it is unresponsive. I can delete the data and re-start, but is that expected?
> Updated: I renamed loki, re-started, and was able to create a new setup and that now works, even with a re-start. So presumably the old data is the issue?
> Additional update: Copied working loki from server and it loads fine. Assuming I corrupted the file with an earlier build I shouldn't have been testing.

See https://github.com/theRAPTLab/meme-2023/wiki/Dataset-Management. 
* `npm run dev` loads `runtime/test.loki`
* `npm run start` loads `runtime/meme.loki`

So your `meme.loki` file was probably corrupt.  We should have automatic data migration in place, but with all the interim dev releases it's quite possible some aspect of the comment system changed.  Check the web console and terminal for error messages.

**Comment by benloh** [comment]
By the way, editing rating labels in the admin should mostly work -- I ended up needing to redo the ratings admin to get it working so I went ahead and restored some of that functionality.  Things might go a little weird if change the number of ratings though.  And it's possible some interim state updates while editing the admin might be wonky, but it looks the ratings data is being saved, so reloading the admin should restore it.

**Comment by jdanish** [comment]
> Things might go a little weird if change the number of ratings though.

This isn't currently a UI option, is it?  Which is fine ... just confirming I am not missing something.

**Comment by benloh** [comment]
> > Things might go a little weird if change the number of ratings though. 
> This isn't currently a UI option, is it? Which is fine ... just confirming I am not missing something.

That's right.  It's not an UI option.  But you can change them programmatically.

**Comment by jdanish** [comment]
Note: the new table has an issue I think we saw ages ago (maybe different table code?) that the initial sort has up and down, not just up or down, and it seems the titles aren't sorting right.

Screenshot 2024-11-17 at 8 16 58 AM

click

Screenshot 2024-11-17 at 8 17 06 AM

click

Screenshot 2024-11-17 at 8 17 13 AM

click

Screenshot 2024-11-17 at 8 17 20 AM

**Comment by benloh** [comment]
Actually it's behaving correctly.
* I wanted to show an "unsorted" view so I used up/down arrow -- I've seen it before, but maybe it's not quite ubiquitous.  I'm open to other suggestions.  Leaving it blank is a possibility I suppose.
* The sorting is case-sensitive.  So U > s > t.  The last view is unsorted.  It seemed important to have an unsorted view.  Perhaps not as important for MEME models lists, but in general tables need to have an unsorted view.

**Comment by jdanish** [comment]
> The sorting is case-sensitive. So U > s > t. The last view is unsorted. It seemed important to have an unsorted view. Perhaps not as important for MEME models lists, but in general tables need to have an unsorted view.

Ahh, so uppercase appear before ALL lowercase, not just their specific letters?  That feels off / not what kids would expect? I'd expect S < s < t or T < U < u ....  

And for un-sorted, OK. Just to be explicit, "unsorted" is technically "default" which likely means "order it was created"?  It's fine so long as I know ...

**Comment by jdanish** [comment]
Note: I'd also be OK ignoring case, but if kids are sorting ben, Ben, and Joshua they definitely expect both Ben's to be together ...

**Comment by benloh** [comment]
I believe it's ASCII order.  So upper case comes before lower case.
* Ben
* Joshua
* Untitiled
* ben
* joshua


With case insensitive, you might get
* ben
* Ben
* ben
* Joshua
* Untitled
Is that OK?

Or are you saying you expect lower case to come before upper?  e.g.
* ben
* ben
* Ben
* Joshua
* Untitled

**Comment by jdanish** [comment]
I’m ok with either depending on which is easier.

**Comment by jdanish** [comment]
I should note I'd imagine the same applies to both net.create and meme

**Comment by benloh** [comment]
Case insensitive is definitely easier than trying to apply a custom sorter that sorts lowercase before uppercase.  You just need to be OK with a sort like this:

* ben
* Ben
* ben    `<-- in the array, the second "ben" appears after the "Ben", so it is displayed last`

**Comment by jdanish** [comment]
Yes that's great thanks!!

**Comment by benloh** [comment]
Case insensitive sorting is now implemented.

**Comment by jdanish** [comment]
Confirmed, and awesome. If you want to merge and then do templating as a separate PR that's cool with me. Or leave this open. Either way, I think table scan be back-ported to net.create at your leisure too (I hope that's really simple).

**Comment by benloh** [comment]
Table backporting should be easy.

But unfortunately there are still a lot of edge cases to work through on the comment side.

**Comment by benloh** [comment]
@jdanish The comment system is finally 99% complete.  I'm chasing down a problem with project comments not updating the count.  But otherwise, I'm going through QA.  201 commits!  The system is complex...

**Comment by jdanish** [comment]
Awesome! Do you want me to have my team test, or wait until your QA pass is done?

**Comment by benloh** [comment]
Please have your team test!  Given the complexity of the system, I'm sure there are more edge conditions that we haven't anticipated.  Hopefully it's just a few minor ones though!

**Comment by jdanish** [comment]
By the way - I really like the functionality that centers the different entities middle of the screen when you look at comments, etc. However, it feels distracting when adding a new entity since I usually position the screen with the top left corner so that I can see as much as possible, but then if I add an entity now it shifts it all down and makes less efficient use of the screen.

If I start here: 
Screenshot 2024-12-08 at 11 24 38 AM

I add "just added", I am shifted here:
Screenshot 2024-12-08 at 11 30 23 AM

I am forced to move it back here: 
Screenshot 2024-12-08 at 11 30 34 AM

It'd be nice to just not re-center in that case if possible.

**Comment by jdanish** [comment]
Also: the mouse-over on entities and processes does not work on the actual diagram currently. If you mouse over the left panel, you see the descriptions, but not from the actual model.

**Comment by jdanish** [comment]
I created a situation on the DO server where Joshua sees that he deleted his comment:

Screenshot 2024-12-09 at 9 55 30 AM

But the other user can still see it ... 

Screenshot 2024-12-09 at 9 56 02 AM

This is at the project level. Is it helpful for you to look at the db?  http://143.244.175.147:3000/#/

Note that the two logins show the comment as a different number, which is odd?

**Comment by jdanish** [comment]
Now that the numbers are out of whack, it seems that the counts are off too?  

Screenshot 2024-12-09 at 9 58 44 AM

UPDATE: I logged back in an hour later, and now could view the comment in both logins, and once deleted it was all correct. So ... seems a caching thing?

**Comment by benloh** [comment]
> So ... seems a caching thing?

@jdanish If you don't mind, creating new issues for these kinds of reports will help us keep better track and have discussions about issues.

In this case, it would be really helpful if you could tell me how to replicate the problem.  This was something that I'd been working through, but I may have not caught all edge cases.

**Comment by benloh** [comment]
To Do
- [x] Don't recenter new props
- [x] Mouseover description for props in diagram
- [x] Check network comment deletion and updates

**Comment by jdanish** [comment]
Cool - will do. Do you need issues now, or moving forward? Thanks!

**Comment by benloh** [comment]
> Cool - will do. Do you need issues now, or moving forward? Thanks!

Thanks!  It'd be helpful if you could write out the comment deletion one.  I thought I had that addressed, but I must be missing an edge case.

**Comment by jdanish** [comment]
OK, trying to reproduce steps now ...

**Comment by jdanish** [comment]
I think the issue is related to what I report in https://github.com/theRAPTLab/meme-2023/issues/100 but will keep tinkering ...

**Comment by benloh** [comment]
Merging.  We'll fix any other issues that come up separately.

**Pull request merged**
